-- This migration was originally generated to add MetodoPagoCliente and contacto fields twice.
-- Those changes were already applied in 20251015123000_checkout_contact_payment_fields.
-- Leaving this file as a no-op keeps the migration history consistent without duplicating objects.
